# ==========================================================================
# CRE PROJECT SETTINGS FILE
# ==========================================================================
# Project-specific settings for CRE CLI targets.

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

# ==========================================================================
monad-settings:
  rpcs:
    - chain-name: monad-testnet
      url: https://testnet-rpc.monad.xyz

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: https://eth.blockrazor.xyz
