# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "weather-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.staging.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
monad-settings:
  user-workflow:
    workflow-name: "weather-monad"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.monad.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "weather-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config/config.production.json"
    secrets-path: "../secrets.yaml"
